[project]
name = "mswar-bot-autopvp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
    "apscheduler>=3.11.0",
    "pycryptodome>=3.23.0",
]
